create table tb_sale (id int8 generated by default as identity, amount float8, date date, deals int4, visited int4, seller_id int8, primary key (id));
create table tb_seller (id int8 generated by default as identity, name varchar(255), primary key (id));
alter table if exists tb_sale add constraint FKbq39pcekpsf8548lxwna2kjgk foreign key (seller_id) references tb_seller;
